#For use on AWS ED env.
#Set version
version: '3.9'
#Define services
services:
  prod-web:
    container_name: my-awesome-app-tmp-aws
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
     - '80:8080'