#Set version
version: '3.9'
#Define services
services:
  web:
    container_name: my-awesome-app-tmp-prod
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - '80:8080'