#Set version
version: '3.9'
#Define services
services:
  web:
    container_name: my-awesome-app-tmp-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-tmp-test
    depends_on: 
      - "web"
    image: my-awesome-app-tmp_web
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: [ "npm", "test" ]